# config.yaml

container:
  image: python:3.9
  name: python_test
  volumes:
    D:\code-project\EasierDocker\example:
      bind: /path/to/container
      mode: rw
  detach: true
  command:
    - sh
    - -c
    - cd /path/to/container && python docker_example.py

network:
  name: bridge
  driver: bridge
